version: "2"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=postgres
      - DB_USER=root
      - DB_PASSWD=your_password
    restart: always
    networks:
      - gitea
    volumes:
      - /mnt/data/gitea:/data
    ports:
      - "80:3000"
      - "22:22"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=your_password
    networks:
      - gitea
    volumes:
      - /mnt/data/postgres:/var/lib/postgresql/data
